#include <stdio.h>

unsigned long long int Hailstone(unsigned long long int n);
int counter = 1;

int main(void)
{
    unsigned long long int n = 0;
    
    while (scanf("%llu", &n) != EOF)
    {
        counter = 1;
        printf("Hailstone generated by %llu:\n%llu", n, n);

        Hailstone(n);

        printf("\nNumber of hailstone generated:%d\n\n", counter);
    }


    return 0;
}

unsigned long long int Hailstone(unsigned long long int n){

    while (n != 1)
    {
        if (!(n % 2))
        {
            n = n / 2;
        }
        else if (n % 2)
        {
            n = 3 * n + 1;
        }
        printf(" %llu", n);
        counter++;
    }

    return 0;
}